### ISSUE TITLE
Correct typos in document example code

### ISSUE THREAD

**Issue by Gumgo91** [volkamerlab/kissim#56]
Hi. I'm hyunseung kong.

https://kissim.readthedocs.io/en/latest/tutorials/api.html#Run-encode-function
Here I found what appears to be a typo in the example code.

I think,
"../../kissim/tests/data/KLIFS_download/"
needs to be change
"kissim/tests/data/KLIFS_download/"

This is a minor, but I'm informing you.

**Comment by dominiquesydow** [comment]
Hi @Gumgo91,

Thanks a lot for reporting this!

The documentation is rendered from Juypter notebooks - the site you are referring to comes from this notebook
https://github.com/volkamerlab/kissim/blob/master/docs/tutorials/api.ipynb
pointing to data that lives in
https://github.com/volkamerlab/kissim/tree/master/kissim/tests/data/KLIFS_download

In context of that notebook the path
`"../../kissim/tests/data/KLIFS_download/"`
is correct, however you are right that it makes no sense when looking at the documentation. 

I will come up with something better - leaving this issue open until I have improved this.

Thanks again!

**Comment by dominiquesydow** [comment]
Adding `kissim.dataset.test` module: We can now load the test data path via `from kissim.dataset.test import PATH as PATH_TEST_DATA`. This avoids setting relative paths within the documentation notebooks. #63
