### ISSUE TITLE
Subset fingerprint by ligand-interacting residues

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/kissim#77]
Use only a subset of residues in the `kissim` fingerprint in the comparison step.

For instance, the subset could contain ligand-interacting residues only:
- For each kinase-ligand combo calculate the average contacts
- Based on (a) DFG-in, (b) DFG-out, or (c) all DFG profiles, extract residues that are in contact with any ligand in at least 1% of the kinases (or structures/monomers?)

List provided by @AJK-dev:

```
DFG-in structures
1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,19,20,21,24,25,27,28,36,37,38,43,44,45,46,47,48,49,50,51,52,54,55,59,70,72,74,75,76,77,80,81,82,83,84,85

DFG-out structures
3,4,5,6,7,8,9,11,12,13,15,16,17,19,20,21,23,24,25,27,28,31,35,36,37,38,43,44,45,46,47,48,49,50,51,52,54,55,60,61,64,66,67,68,69,70,74,75,77,79,80,81,82,83,84,85

Min 1% in any DFG profile
1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,19,20,21,23,24,25,27,28,31,35,36,37,38,41,43,44,45,46,47,48,49,50,51,52,53,54,55,56,59,60,61,64,66,67,68,69,70,72,74,75,76,77,79,80,81,82,83,84,85
```

**Comment by AJK-dev** [comment]
> Based on (a) DFG-in, (b) DFG-out, or (c) all DFG profiles, extract residues that are in contact with any ligand in at least 1% of the kinases (or structures/monomers?)

This was based on ≥1% interaction frequency across the unique kinase-ligand combinations. For each kinase-ligand combination, the average frequency of the residue-ligand contact was calculated based on the available IFPs. So all monomers and structures with the same kinase-ligand combination were taken into account during this analysis.

**Comment by dominiquesydow** [comment]
Perfect, thanks @AJK-dev for the clarification!
